title: My Personal Blog
description: 'A Branch of non-profit organization, McmpAcme, Inc.'
baseurl: /
url: 'https://mrcklinn.github.io/'
github_repo: jekyll
github_username: mrcklinn
social_link: twitter
social_username: mrcklinn
theme_color: gray
markdown: markdown
